"""Contrastive training datasets, losses, and trainer."""

__all__ = [
    "SupConLoss",
    "trainer",
    "ALLNLI",
    "AMAZONQA",
    "CONCURRENTQA",
    "FEVER",
    "GITHUBISSUE",
    "GOOAQ",
    "MSMARCO",
    "PAQ",
    "PUBMEDQA",
    "QQP",
    "SENTENCECOMP",
    "STACKEXCHANGE",
    "STACKOVERFLOW",
    "STS12",
    "STSBENCHMARK",
    "TRIVIAQA",
    "WIKIHOW",
    "CONTRASTIVE_DATASETS",
    "discover_cached_contrastive_dataset_names",
    "load_cached_contrastive_datasets",
    "normalize_contrastive_dataset_name_token",
    "resolve_contrastive_dataset_name",
    "resolve_contrastive_dataset_names",
]

from .datasets import (
    ALLNLI,
    AMAZONQA,
    CONTRASTIVE_DATASETS,
    CONCURRENTQA,
    discover_cached_contrastive_dataset_names,
    FEVER,
    GITHUBISSUE,
    GOOAQ,
    load_cached_contrastive_datasets,
    MSMARCO,
    normalize_contrastive_dataset_name_token,
    PAQ,
    PUBMEDQA,
    QQP,
    resolve_contrastive_dataset_name,
    resolve_contrastive_dataset_names,
    SENTENCECOMP,
    STACKEXCHANGE,
    STACKOVERFLOW,
    STS12,
    STSBENCHMARK,
    TRIVIAQA,
    WIKIHOW,
)
from .loss import SupConLoss
from .trainer import trainer
