task: "pretraining"

model:
  hidden_size: 768
  num_hidden_layers: 12
  num_attention_heads: 12
  intermediate_size: 3072
  dropout_prob: 0.05
  vocab_size: 31999
  max_position_embeddings: 4096
  flash_attention: true
  ngpt: false
  hidden_act: "swiglu"  # Requires xformers
  rope: true
  rms_norm: true

dataset:
  name: "EleutherAI/SmolLM2-1.7B-stage-4-100B"
  streaming: true  # Stream this large dataset
  num_proc: 8
  num_workers: 4
  max_seq_length: 1024
  train_split: "train"
  eval_split: "train[:1%]"  # Use small subset for eval

tokenizer:
  name: "BEE-spoke-data/wordpiece-tokenizer-32k-en_code-msp"
  vocab_size: 31999
  max_length: 1024

datacollator:
  mlm_probability: 0.2
  pad_to_multiple_of: 8

trainer:
  output_dir: "./outputs/neobert_100m_100k"
  run_name: "neobert-100m-100k-managed"
  max_steps: 100000
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 4
  learning_rate: 1e-4
  warmup_steps: 5000
  logging_steps: 25
  eval_steps: 5000
  save_steps: 10000  # Save every 10k steps
  save_total_limit: 3  # Keep only last 3 checkpoints (30k, 20k, 10k won't be kept)
  max_ckpt: 3  # Alternative checkpoint limit
  dataloader_num_workers: 4
  remove_unused_columns: false
  report_to: ["wandb"]
  bf16: true
  gradient_checkpointing: false
  resume_from_checkpoint: false

optimizer:
  name: "adamw"
  lr: 1e-4
  weight_decay: 0.01
  betas: [0.9, 0.98]
  eps: 1e-8

scheduler:
  name: "cosine"
  warmup_steps: 5000
  total_steps: 100000

wandb:
  project: "neobert-pretraining"
  name: "neobert-100m-100k-managed"
  mode: "online"
  tags: ["100m", "100k-steps", "smollm2-data", "managed-checkpoints"]

# Additional settings
seed: 42
mixed_precision: "bf16"