task: "pretraining"

model:
  hidden_size: 768
  num_hidden_layers: 28  # Full NeoBERT size (250M params)
  num_attention_heads: 12
  intermediate_size: 3072
  dropout_prob: 0.1
  vocab_size: 31999  # BEE-spoke-data tokenizer vocab size
  max_position_embeddings: 1024  # Context length as requested
  flash_attention: true
  ngpt: false
  hidden_act: "swiglu"  # Requires xformers
  rope: true
  rms_norm: true

dataset:
  name: "EleutherAI/SmolLM2-1.7B-stage-4-100B"
  streaming: true  # Stream this large dataset
  num_proc: 16
  num_workers: 4
  max_seq_length: 1024
  train_split: "train"
  eval_split: "train[:1%]"  # Use small subset for eval

tokenizer:
  name: "BEE-spoke-data/wordpiece-tokenizer-32k-en_code-msp"
  vocab_size: 31999
  max_length: 1024

datacollator:
  mlm_probability: 0.15
  pad_to_multiple_of: 8

trainer:
  output_dir: "./outputs/smollm2_custom_tokenizer"
  run_name: "neobert_250m_smollm2_32k"
  max_steps: 100000  # 100k steps as requested
  per_device_train_batch_size: 16  # Reduced for 250M model
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 4  # Increased to maintain effective batch size
  learning_rate: 1e-4
  warmup_steps: 5000
  logging_steps: 100
  eval_steps: 5000
  save_steps: 10000
  dataloader_num_workers: 4
  remove_unused_columns: false
  report_to: ["wandb"]
  bf16: true
  gradient_checkpointing: false
  resume_from_checkpoint: false

optimizer:
  name: "adamw"
  lr: 1e-4
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1e-8

scheduler:
  name: "cosine"
  warmup_steps: 5000
  total_steps: 100000

wandb:
  project: "neobert-smollm2"
  name: "smollm2-32k-tokenizer-100k"
  mode: "online"

# Additional settings
seed: 42
mixed_precision: "bf16"