task: "pretraining"

model:
  hidden_size: 768
  num_hidden_layers: 12
  num_attention_heads: 12
  intermediate_size: 3072
  dropout_prob: 0.1
  vocab_size: 30522
  max_position_embeddings: 512
  flash_attention: true  # Now available with flash-attn 2.7.3
  ngpt: false
  hidden_act: "swiglu"  # Default activation (requires xformers)
  rope: true
  rms_norm: true

dataset:
  name: "wikipedia"  # Change to your dataset
  path: null
  streaming: true
  num_proc: 16
  num_workers: 4
  max_seq_length: 512
  train_split: "train[:1%]"  # Use small subset for testing
  eval_split: "train[99%:]"

tokenizer:
  name: "bert-base-uncased"
  vocab_size: 30522
  max_length: 512

datacollator:
  mlm_probability: 0.15
  pad_to_multiple_of: 8

trainer:
  output_dir: "./outputs/neobert_pretrain"
  run_name: "neobert_pretrain"
  max_steps: 1000000
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 1
  learning_rate: 1e-4
  warmup_steps: 10000
  logging_steps: 100
  eval_steps: 10000
  save_steps: 10000
  dataloader_num_workers: 4
  remove_unused_columns: false
  report_to: ["wandb"]  # Remove if you don't want logging
  fp16: false
  bf16: true  # Use bf16 on modern GPUs
  gradient_checkpointing: false
  resume_from_checkpoint: false

optimizer:
  name: "adamw"
  lr: 1e-4
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1e-8

scheduler:
  name: "cosine"
  warmup_steps: 10000
  total_steps: 1000000

wandb:
  project: "neobert-pretraining"
  mode: "online"

# Additional settings
seed: 42
mixed_precision: "bf16"
EOF < /dev/null